#!/bin/sh

set -xe

mkdir -p ~/opt/
cp git-sl ~/opt/
cp git-status-ls.sh ~/opt/

if [[ "$(uname -s)" =~ ^MSYS_NT.* ]]; then
  git config --global core.excludesfile ~/.gitignore
  cp .gitignore ~/
  cp .vimrc ~/
else
  git config --global core.excludesfile ~/.gitignore
  ln -s $(pwd)/.gitignore ~/.gitignore
  ln -s $(pwd)/.vimrc ~/.vimrc
fi
