#!/bin/sh

mkdir -p ~/opt/
cp git-sl ~/opt/
cp git-status-ls.sh ~/opt/

if [[ "$(uname -s)" =~ ^MSYS_NT.* ]]; then
  cp .gitignore ~/
  cp .vimrc ~/
else
    ln -s .gitignore ~/.gitignore
    ln -s .vimrc ~/.vimrc
fi
